
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package sculk.of.ixra.init;

import sculk.of.ixra.SculksOfArdaMod;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

public class SculksOfArdaModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, SculksOfArdaMod.MODID);
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_WEAPONS = REGISTRY.register("ardas_sculks_weapons",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_weapons")).icon(() -> new ItemStack(SculksOfArdaModItems.SCULKERITE_SWORD.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModItems.SCULK_ARMS.get());
				tabData.accept(SculksOfArdaModItems.GOLDEN_SCULK_ARMS.get());
				tabData.accept(SculksOfArdaModItems.NETHERITE_SCULK_ARM.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_SCULK_ARM.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_SCULK_ARM.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ARMOR_HELMET.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ARMOR_CHESTPLATE.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ARMOR_LEGGINGS.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ARMOR_BOOTS.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_ARMOR_HELMET.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_ARMOR_CHESTPLATE.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_ARMOR_LEGGINGS.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_ARMOR_BOOTS.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_SWORD.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_PICKAXE.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_AXE.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_SWORD.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_LONG_SWORD.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_HAMMER.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_PAXEL.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_SHOVEL.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_HOE.get());
				tabData.accept(SculksOfArdaModItems.SCULK_BOW.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ARROW_ITEM.get());
				tabData.accept(SculksOfArdaModItems.SCULK_WORLD.get());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_PICKAXE.get());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_AXE.get());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_SWORD.get());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_SHOVEL.get());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_HOE.get());
				tabData.accept(SculksOfArdaModItems.BLACKBIRCHPLANKSPICKAXE.get());
				tabData.accept(SculksOfArdaModItems.BLACKBIRCHPLANKSAXE.get());
				tabData.accept(SculksOfArdaModItems.BLACKBIRCHPLANKSSWORD.get());
				tabData.accept(SculksOfArdaModItems.BLACKBIRCHPLANKSSHOVEL.get());
				tabData.accept(SculksOfArdaModItems.BLACKBIRCHPLANKSHOE.get());
				tabData.accept(SculksOfArdaModItems.WISTERYA_WOODEN_PICKAXE.get());
				tabData.accept(SculksOfArdaModItems.WISTERYA_WOODEN_AXE.get());
				tabData.accept(SculksOfArdaModItems.WISTERYA_WOODEN_SWORD.get());
				tabData.accept(SculksOfArdaModItems.WISTERYA_WOODEN_SHOVEL.get());
				tabData.accept(SculksOfArdaModItems.WISTERYA_WOODEN_HOE.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_WOODEN_PICKAXE.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_WOODEN_AXE.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_WOODEN_SWORD.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_WOODEN_SHOVEL.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_WOODEN_HOE.get());
			}).withSearchBar().build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS = REGISTRY.register("ardas_sculks",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks")).icon(() -> new ItemStack(SculksOfArdaModItems.GOLDEN_SCULK_SENSOR_PART.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModItems.SCULK_PIECE.get());
				tabData.accept(SculksOfArdaModItems.SCULK_SENSOR_PART.get());
				tabData.accept(SculksOfArdaModItems.WARDEN_CLAWS.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_SCULK_PIECE.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_SCULK_SENSOR_PART.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_WARDEN_CLAWS.get());
				tabData.accept(SculksOfArdaModItems.DEEP_DARK_UPGRADE_TEMPLATE.get());
				tabData.accept(SculksOfArdaModItems.GOLDEN_SCULK_PIECE.get());
				tabData.accept(SculksOfArdaModItems.GOLDEN_SCULK_SENSOR_PART.get());
				tabData.accept(SculksOfArdaModItems.GOLDEN_WARDEN_CLAWS.get());
				tabData.accept(SculksOfArdaModItems.ROTTEN_CREAKING_SHELL.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_UPGRADE_SMITHING_TEMPLATE.get());
				tabData.accept(SculksOfArdaModItems.BUCKET_FILLED_WITH_RAW_IRON.get());
				tabData.accept(SculksOfArdaModItems.BUCKET_FILLED_WITH_SCULK.get());
				tabData.accept(SculksOfArdaModItems.MOLTEN_IRON_BUCKET.get());
				tabData.accept(SculksOfArdaModItems.MOLTEN_SCULK_BUCKET.get());
				tabData.accept(SculksOfArdaModItems.ANCIENTNAUTILUSSHELL.get());
				tabData.accept(SculksOfArdaModItems.AGILE_SLIME_BALL.get());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_WEAPONS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_BLOCKS = REGISTRY.register("ardas_sculks_blocks",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_blocks")).icon(() -> new ItemStack(SculksOfArdaModBlocks.SCULK_BRICK.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_CARVED.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_CARVED_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_CARVED_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICK_CARVED_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CUT_SCULK_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CUT_SCULK_BLOCK_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CUT_SCULK_BLOCK_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CUT_SCULK_BLOCK_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_SMOOLIGHT.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LIGHT.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEPSLATE_BULB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.THORNY_DEEPSLATE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.TRAPPED_DEEPSLATE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.MOSSY_DEEPSLATE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEPSLATE_BOOKSHELF.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CARVED_PUMKIN.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_MUSHROOM_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_SAND.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_STONE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_STONE_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_STONE_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_STONE_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RESIN_ANCIENT_GRANITE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_GRANITE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_GRANITE_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_GRANITE_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_GRANITE_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_MOSS_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_EYE_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_GRASS_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.FLOWERING_SCULK_GRASS_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_GRASS_PATH_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.MYCELIUM_SCULK_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SOUL_SCULK_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_SCULK_GRASS_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_SCULK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKRESINBRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKRESINBLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BLOCK_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BLOCK_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BLOCK_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_SCULK_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROCK_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROCK_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROCK_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_TINY_ROCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_THORNS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_STONE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_STONE_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_STONE_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_STONE_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CRYING_SACRED_OBSIDIAN_STONE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CRYING_SACRED_OBSIDIAN_STONE_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CRYING_SACRED_OBSIDIAN_STONE_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CRYING_SACRED_OBSIDIAN_STONE_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_NAUTILUS_SHELL_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.AGILE_SLIME_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_MAGMA.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.MOSSY_DEEP_GRANULITE_STONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_DEEP_GRANULITE_STONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CHISELED_DEEP_GRANULITE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_STONE_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.POLISHED_DEEP_GRANULITE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.COMPRESSED_DEEP_GRANULITE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CARVED_VERTICAL_COLUMN_DEEPSLATE_STONE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKERITE_DEEPSLATE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKERITE_DEEPSLATE_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKERITE_DEEPSLATE_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKERITE_DEEPSLATE_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BLOCK_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BLOCK_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BLOCK_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKED_BONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.CRACKED_SCULK_BONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_TILES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_TILES_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_TILES_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_TILES_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_BONE_GLASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULKED_CRYSTAL_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_BRICKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_BRICKS_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_BRICKS_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_BRICKS_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_TILES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_TILES_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_TILES_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_TILES_WALL.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_BARS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_DOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_TRAPDOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_GLASS.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_MATERIALS = REGISTRY.register("ardas_sculks_materials",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_materials")).icon(() -> new ItemStack(SculksOfArdaModItems.SCULK_INGOT.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModItems.SCULK_INGOT.get());
				tabData.accept(SculksOfArdaModItems.SCULKERITE_NUGGET.get());
				tabData.accept(SculksOfArdaModBlocks.SCULK_INGOT_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModItems.SCULKED_EMERALD.get());
				tabData.accept(SculksOfArdaModBlocks.SCULKED_EMERALD_BLOCK.get().asItem());
				tabData.accept(SculksOfArdaModItems.SACRED_OBSIDIAN_SHARD.get());
				tabData.accept(SculksOfArdaModItems.SCULK_CRYSTAL.get());
				tabData.accept(SculksOfArdaModItems.SCULK_RESIN_CLUMP.get());
				tabData.accept(SculksOfArdaModItems.SCULKRESINBRICK.get());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_BLOCKS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_MINECRAFT_ORES = REGISTRY.register("ardas_minecraft_ores",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_minecraft_ores")).icon(() -> new ItemStack(SculksOfArdaModBlocks.EMERALD_SCULK_ORE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.DIAMOND_SCULK_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.GOLD_SCULK_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.EMERALD_SCULK_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.QUARTZ_SCULK_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SACRED_OBSIDIAN_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_GOLD_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_DIAMOND_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_ANCIENT_DEBRIS_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_EMERALD_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_AMETHYS_ORE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRANULITE_SCULKERITE_ORE.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_MATERIALS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_MACHINES = REGISTRY.register("ardas_sculks_machines",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_machines")).icon(() -> new ItemStack(SculksOfArdaModBlocks.ADVANCED_FURNACE_ON.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.ADVANCED_FURNACE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CHEST.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEPSLATE_DISPENSER.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_MINECRAFT_ORES.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_PLANTS = REGISTRY.register("ardas_sculks_plants",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_plants")).icon(() -> new ItemStack(SculksOfArdaModBlocks.SCULK_FUNGUS.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.SCULK_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_SPROUTS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_FUNGUS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.TALL_SCULK_MUSHROOM.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_ROOTS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.TALL_SCULK_PLANT.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SOUL_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SOUL_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CACTUS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_VINES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.TALL_SCULK_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.FADED_ANTIQUE_SHORT_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.FADED_ANTIQUE_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WITHERED_ANCIENT_SHRUB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WILTED_ANCIENT_TREE_PLANT.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_CREAKING_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.ANCIENT_CREAKING_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_TALL_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_BUSH.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_TALL_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_WART.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROOTS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_ROSE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.OBSIDIAN_THORN.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_FLOWER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_MUSHROOM.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.DEEP_ROOTS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_MUSHROOM.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BUSH.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_GRASS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_CRYSTAL_CLUSTER.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_MACHINES.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_MOBS = REGISTRY.register("ardas_sculks_mobs",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_mobs")).icon(() -> new ItemStack(SculksOfArdaModItems.SCULK_CREEPER_SPAWN_EGG.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModItems.SCULK_CREEPER_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_SKELETON_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_ENDERMAN_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_CREAKING_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_FISH_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_FOX_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.AGILE_SLIME_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_GHOST_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SCULK_GOLEM_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_WARDEN_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModItems.SHADOW_HUNTER_SPAWN_EGG.get());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_WARDEN_SPAWNER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_GOLEM_SPAWNER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_MOB_SPAWNER.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SHADOW_HUNTER_SPAWNER.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_PLANTS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> LOG_BLOCKS = REGISTRY.register("log_blocks",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.log_blocks")).icon(() -> new ItemStack(SculksOfArdaModBlocks.SCULK_LOG_PLANKS.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_SCULK_LOG_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_SCULK_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_PLANKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_LEAVES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_FENCE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_FENCE_GATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_PRESSURE_PLATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_LOG_BUTTON.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_PLANKS_CRAFTING_TABLE.get().asItem());
				tabData.accept(SculksOfArdaModItems.SCULK_PLANKS_STICK.get());
				tabData.accept(SculksOfArdaModBlocks.SCULK_WOODEN_DOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_WOODEN_TRAPDOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_BLACK_BIRCH_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_BLACK_BIRCH_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.SCULK_RESIN_BLACK_BIRCH_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_PLANKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_LEAVES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_FENCE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_FENCE_GATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_PRESSURE_PLATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_BUTTON.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_CRAFTING_TABLE.get().asItem());
				tabData.accept(SculksOfArdaModItems.BLACK_BIRCH_STICK.get());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_WOODEN_DOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.BLACK_BIRCH_WOODEN_TRAPDOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_WISTERYA_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_WISTERYA_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.MOSSY_WISTERY_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_PLANKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_LEAVES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_FENCE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_FENCE_GATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_PRESSURE_PLATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_BUTTON.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_CRAFTING_TABLE.get().asItem());
				tabData.accept(SculksOfArdaModItems.WISTERYA_STICK.get());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_WOODEN_DOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.WISTERYA_WOODEN_TRAPDOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_RADIOACTIVE_BALSA_WOOD.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.STRIPPED_RADIOACTIVE_BALSA_LOG.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_PLANKS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_LEAVES.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_STAIRS.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_SLAB.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_FENCE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_FENCE_GATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_PRESSURE_PLATE.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_BUTTON.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_CRAFTING_TABLE.get().asItem());
				tabData.accept(SculksOfArdaModItems.RADIOACTIVE_BALSA_STICK.get());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_WOODEN_DOOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_BALSA_WOODEN_TRAPDOOR.get().asItem());
			}).withSearchBar().withTabsBefore(ARDAS_SCULKS_MOBS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_SENSORS = REGISTRY.register("ardas_sculks_sensors",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_sensors")).icon(() -> new ItemStack(SculksOfArdaModBlocks.SOUL_SCULK_SENSOR.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModBlocks.SOUL_SCULK_SENSOR.get().asItem());
				tabData.accept(SculksOfArdaModBlocks.RADIOACTIVE_SCULK_SENSOR.get().asItem());
			}).withTabsBefore(LOG_BLOCKS.getId()).build());
	public static final DeferredHolder<CreativeModeTab, CreativeModeTab> ARDAS_SCULKS_FOODS = REGISTRY.register("ardas_sculks_foods",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.sculks_of_arda.ardas_sculks_foods")).icon(() -> new ItemStack(SculksOfArdaModItems.SWEET_PALE_CAKE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(SculksOfArdaModItems.SCULK_RESIN_APPLE.get());
				tabData.accept(SculksOfArdaModItems.CREAKING_COOKIE.get());
				tabData.accept(SculksOfArdaModItems.SWEET_PALE_CAKE.get());
			}).withTabsBefore(ARDAS_SCULKS_SENSORS.getId()).build());
}
